create extension if not exists postgis;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,role text not null default 'user' check(role in ('user','admin')),trust_score numeric not null default .5,created_at timestamptz default now());
create table if not exists public.bumps(id uuid primary key default gen_random_uuid(),lat double precision not null check(lat between -90 and 90),lng double precision not null check(lng between -180 and 180),geom geography(Point,4326) generated always as (st_setsrid(st_makepoint(lng,lat),4326)::geography) stored,type text not null default 'speed_bump' check(type in ('speed_bump','road_hump','pothole','rumble','unknown')),severity text not null default 'medium' check(severity in ('low','medium','high')),note text,status text not null default 'active' check(status in ('active','hidden','review')),confidence numeric not null default .5 check(confidence between 0 and 1),confirmations int not null default 0,reports int not null default 0,source text not null default 'manual' check(source in ('manual','sensor_auto')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz default now(),updated_at timestamptz default now());
create index if not exists bumps_geom_idx on public.bumps using gist(geom);
create table if not exists public.bump_votes(id uuid primary key default gen_random_uuid(),bump_id uuid references public.bumps(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,kind text not null check(kind in ('confirm','report')),created_at timestamptz default now(),unique(bump_id,user_id));
alter table public.profiles enable row level security; alter table public.bumps enable row level security; alter table public.bump_votes enable row level security;
create policy "public active bumps" on public.bumps for select using(status='active' or auth.uid()=created_by);
create policy "users add bumps" on public.bumps for insert with check(auth.uid()=created_by);
create policy "users update own" on public.bumps for update using(auth.uid()=created_by);
create policy "vote insert own" on public.bump_votes for insert with check(auth.uid()=user_id);
create policy "vote read own" on public.bump_votes for select using(auth.uid()=user_id);
create policy "profiles own" on public.profiles for select using(auth.uid()=id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))) on conflict do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.vote_bump(p_bump_id uuid,p_kind text) returns void language plpgsql security definer as $$ begin if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if; insert into public.bump_votes(bump_id,user_id,kind) values(p_bump_id,auth.uid(),p_kind); if p_kind='confirm' then update public.bumps set confirmations=confirmations+1,confidence=least(1,confidence+.05),updated_at=now() where id=p_bump_id; else update public.bumps set reports=reports+1,confidence=greatest(0,confidence-.1),status=case when reports+1 >= confirmations+3 then 'review' else status end,updated_at=now() where id=p_bump_id; end if; exception when unique_violation then raise exception 'لقد صوّت لهذا الموقع مسبقًا'; end; $$;
-- Geo query example:
-- select id,lat,lng,type,severity,confidence,st_distance(geom,st_setsrid(st_makepoint(:lng,:lat),4326)::geography) meters from public.bumps where status='active' and st_dwithin(geom,st_setsrid(st_makepoint(:lng,:lat),4326)::geography,2000) order by meters limit 200;
