const KEY='matbak_bumps_v2';
const seed=[{id:'1',lat:21.5439,lng:39.1741,type:'مرتفع',severity:5,visibility:4,confidence:91,confirmations:34,rating:4.7},{id:'2',lat:21.5418,lng:39.1697,type:'عادي',severity:3,visibility:5,confidence:88,confirmations:22,rating:4.3},{id:'3',lat:21.5460,lng:39.1760,type:'طويل',severity:4,visibility:3,confidence:76,confirmations:11,rating:4.1}];
let bumps=JSON.parse(localStorage.getItem(KEY)||'null')||seed, pos=null, watch=null, driving=false, muted=false, userMarker=null, markers=[], selected=null;
const map=L.map('map').setView([21.543333,39.172778],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);
const $=id=>document.getElementById(id);const save=()=>localStorage.setItem(KEY,JSON.stringify(bumps));
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').style.display='none',3200)}
function dist(a,b,c,d){const R=6371000,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function bear(a,b,c,d){const p1=a*Math.PI/180,p2=c*Math.PI/180,dl=(d-b)*Math.PI/180,y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function ad(a,b){return Math.abs(((a-b+540)%360)-180)}function speak(t){if(muted)return;if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='ar-SA';u.rate=.95;speechSynthesis.speak(u)}}
function render(){markers.forEach(m=>m.remove());markers=[];bumps.forEach(b=>{const icon=L.divIcon({className:'',html:'<div style="width:38px;height:38px;border-radius:50%;background:#ff6b4a;border:3px solid #fff;display:grid;place-items:center;font-size:19px;box-shadow:0 4px 15px #0008">⚠️</div>',iconSize:[38,38],iconAnchor:[19,19]});let m=L.marker([b.lat,b.lng],{icon}).addTo(map);m.on('click',()=>openDetails(b));markers.push(m)});$('count').textContent=bumps.length+' مطب مسجل';$('trusted').textContent=bumps.filter(b=>b.confidence>=80).length;$('confirmed').textContent=bumps.reduce((n,b)=>n+b.confirmations,0);save()}
function setPosition(p,center=false){pos=p;if(!userMarker){const icon=L.divIcon({className:'',html:'<div style="width:40px;height:40px;border-radius:50%;background:#1976ff;border:3px solid #fff;display:grid;place-items:center;font-size:20px">🚗</div>',iconSize:[40,40],iconAnchor:[20,20]});userMarker=L.marker([p.lat,p.lng],{icon,zIndexOffset:1000}).addTo(map)}else userMarker.setLatLng([p.lat,p.lng]);$('gpsStatus').textContent='متصل';if(center)map.setView([p.lat,p.lng],17);checkNearest()}
function locate(){if(!navigator.geolocation)return toast('GPS غير متاح في هذا المتصفح.');navigator.geolocation.getCurrentPosition(p=>setPosition({lat:p.coords.latitude,lng:p.coords.longitude},true),()=>toast('اسمح بالوصول إلى الموقع.'))}
$('locate').onclick=locate;$('mypos').onclick=locate;
function startDrive(){if(!navigator.geolocation)return toast('هذا المتصفح لا يدعم GPS.');driving=true;$('start').classList.add('hidden');$('drive').classList.remove('hidden');$('speedBox').classList.remove('hidden');$('modeTitle').textContent='وضع القيادة';watch=navigator.geolocation.watchPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude});$('speed').textContent=Math.round((p.coords.speed||0)*3.6)},()=>toast('تعذر قراءة موقعك.'),{enableHighAccuracy:true,maximumAge:1000,timeout:10000})}
$('startDrive').onclick=startDrive;$('stopDrive').onclick=()=>{driving=false;if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;$('start').classList.remove('hidden');$('drive').classList.add('hidden');$('speedBox').classList.add('hidden');$('warning').classList.add('hidden');$('modeTitle').textContent='الخريطة الرئيسية'};$('voice').onclick=()=>{muted=!muted;$('voice').textContent=muted?'🔇':'🔊'};$('muteDrive').onclick=()=>{muted=!muted;$('muteDrive').textContent=muted?'🔇 الصوت مكتوم':'🔊 الصوت يعمل'};
function checkNearest(){if(!driving||!pos)return;let h=null;let list=bumps.map(b=>({...b,d:dist(pos.lat,pos.lng,b.lat,b.lng),br:bear(pos.lat,pos.lng,b.lat,b.lng)})).filter(b=>b.d<1200);if(list.length)h=list.sort((a,b)=>a.d-b.d)[0];if(!h)return;$('distance').textContent=Math.round(h.d)+' متر';let msg=h.d<50?'⚠️ مطب قريب جدًا، خفف السرعة الآن.':h.d<150?'⚠️ مطب قريب، خفف السرعة.':h.d<350?'⚠️ مطب أمامك، استعد لخفض السرعة.':'⚠️ مطب أمامك.';$('warningText').textContent=msg;$('warning').classList.toggle('hidden',h.d>700);if(h.d<350){let now=Date.now();if(!window.lastWarn||now-window.lastWarn>15000){window.lastWarn=now;speak(msg);toast(msg)}}}
function openDetails(b){selected=b;$('modalTitle').textContent='تفاصيل المطب';$('modalBody').innerHTML=`<div style="background:#241a18;padding:12px;border-radius:13px"><b>مطب ${b.type}</b><br><small>موثوقية المجتمع: ${b.confidence}%</small></div><p>الارتفاع: <span class="stars">${'★'.repeat(b.severity)}${'☆'.repeat(5-b.severity)}</span></p><p>الوضوح: <span class="stars">${'★'.repeat(b.visibility)}${'☆'.repeat(5-b.visibility)}</span></p><p>التقييم: <b>${b.rating||'جديد'}</b></p><div class="coords">📍 ${b.lat.toFixed(6)}, ${b.lng.toFixed(6)}</div><div class="actions"><button class="yes" onclick="confirmBump(true)">✓ موجود</button><button class="no" onclick="confirmBump(false)">× غير موجود</button></div><button class="save" onclick="editBump()">✎ تصحيح الموقع والبيانات</button>`;$('modal').classList.remove('hidden')}
window.confirmBump=ok=>{bumps=bumps.map(b=>b.id===selected.id?{...b,confirmations:b.confirmations+(ok?1:0),confidence:Math.max(0,Math.min(99,b.confidence+(ok?3:-8)))}:b);render();toast(ok?'تم تأكيد وجود المطب.':'تم تسجيل أن المطب غير موجود.');closeModal()};
window.editBump=()=>{$('modalTitle').textContent='تعديل المطب';$('modalBody').innerHTML=`<label>نوع المطب<select id="etype"><option>عادي</option><option>مرتفع</option><option>طويل</option><option>غير واضح</option></select></label><label>الشدة <input id="esev" type="range" min="1" max="5" value="${selected.severity}"></label><div class="coords">📍 ${selected.lat.toFixed(6)}, ${selected.lng.toFixed(6)}</div><button class="save" onclick="saveEdit()">حفظ التعديل</button>`;$('etype').value=selected.type};window.saveEdit=()=>{bumps=bumps.map(b=>b.id===selected.id?{...b,type:$('etype').value,severity:+$('esev').value}:b);render();toast('تم حفظ التعديل.');closeModal()};
function closeModal(){$('modal').classList.add('hidden')}$('close').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('add').onclick=()=>{if(!pos){locate();toast('حدد موقعك أولًا ثم اضغط إضافة مطب.');return}let b={id:crypto.randomUUID(),lat:pos.lat,lng:pos.lng,type:'عادي',severity:3,visibility:3,confidence:50,confirmations:0,rating:0};bumps.unshift(b);render();selected=b;openDetails(b);toast('تمت إضافة مطب جديد في موقعك.')};render();
